/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import archivo.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import logica.*;

/**
 *
 * @author Sebastian Burgos
 */
public class AgregarSerie extends javax.swing.JFrame {

    private ManipulaSerie manipulador;
    /**
     * Creates new form SerieNew
     */
    public AgregarSerie() {
        //Evita que se pueda maximizar la pestaña
        this.setResizable(false);
        //Centrar la pestaña
        //this.setLocationRelativeTo(null);
        cargarSeries();
        initComponents();
        recargarSeries();
    }
    
    public void cargarSeries(){
        manipulador = new ManipulaSerie();
        LeerManipulaPro lector = new LeerManipulaPro();
        try{
            if (lector.abrirArchivo()) {
                //Se lee el objeto y se asigna al atributo de la clase VentanaPrincipal.
                manipulador = (ManipulaSerie)lector.leerArchivo();
                //Se cierra la conexión.
                lector.cerrarArchivo();
            }
        }
        catch(Exception e){ 
            System.err.println("Error en leer archivo series");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreSerie = new javax.swing.JTextField();
        txtAnioCreacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSeriesExistentes = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrarSerie = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(187, 198, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Serie");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 60));
        jPanel1.add(txtNombreSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 290, 30));
        jPanel1.add(txtAnioCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 290, 30));

        txtSeriesExistentes.setToolTipText("");
        txtSeriesExistentes.setVisibleRowCount(6);
        jScrollPane1.setViewportView(txtSeriesExistentes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 210, 100));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Series existentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 230, 130));

        btnRegistrarSerie.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarSerie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarSerie.setText("REGISTRAR SERIE");
        btnRegistrarSerie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSerieActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 200, 50));

        jLabel5.setLabelFor(txtNombreSerie);
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre de la serie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 310, 60));

        jLabel2.setLabelFor(txtAnioCreacion);
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Año de creacion"));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 310, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSerieActionPerformed
        try{
            String nombreSerie = txtNombreSerie.getText();
            int anioCreacion = Integer.parseInt(txtAnioCreacion.getText());
            if(!nombreSerie.equals("") && anioCreacion>1700){
                if(manipulador.agregarSerie(new Serie(nombreSerie,anioCreacion))){
                    escribirArchivoSeries();
                }
                else{                    
                    JOptionPane.showMessageDialog(null, "Ya existe una serie con estos datos","",JOptionPane.WARNING_MESSAGE);
                }
                recargarSeries();
            }
            else{
                JOptionPane.showMessageDialog(null,"Todos los cambos deben ser llenados","Error datos",JOptionPane.WARNING_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Hubo un problema: " + e,"Error datos",JOptionPane.WARNING_MESSAGE);
        }
            
    }//GEN-LAST:event_btnRegistrarSerieActionPerformed

    private void escribirArchivoSeries(){
        EscribirManipulaPro escribir = new EscribirManipulaPro();
        escribir.abrirArchivo();
        escribir.escribirObjeto(manipulador);
        escribir.cerrarArchivo();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarSerie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarSerie;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAnioCreacion;
    private javax.swing.JTextField txtNombreSerie;
    private javax.swing.JList<String> txtSeriesExistentes;
    // End of variables declaration//GEN-END:variables

    private void recargarSeries(){
        this.txtNombreSerie.setText("");
        this.txtAnioCreacion.setText("");
        ArrayList <String> datosSeries = new ArrayList<>();
        if(manipulador!=null){
            for(Serie serie: manipulador.getSeries()){
                datosSeries.add(serie.getNombreSerie()+"---"+serie.getYearCreacion()+"\n");
            }
            DefaultListModel listModel = new DefaultListModel();
            for (int i = 0; i < datosSeries.size(); i++)
            {
                listModel.addElement(datosSeries.get(i));
            }
            this.txtSeriesExistentes.setModel(listModel);            
        }                    
    }
    /*
    private Boolean validarSerie(String nombre,int anioCreacion){
        for(Serie serie: manipulador.getSeries()){
            if(serie.getNombreSerie().equalsIgnoreCase(nombre) && serie.getYearCreacion()==anioCreacion){
                return false;
            }
        }
        return true;
    }*/
}
