/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import archivo.LeerArchivoHeroe;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Heroe;

/**
 *
 * @author Sebastian Burgos
 */
public class BuscarPersonajeHeroe extends javax.swing.JFrame {
    private ArrayList<Heroe> listSuperHeroes;
    /**
     * Creates new form AgregarPersonaje
     */
    public BuscarPersonajeHeroe() {
        //Evita que se pueda maximizar la pestaña
        this.setResizable(false);
        llenarDatosSuperHeroes();
        initComponents();
    }
    
    private void llenarDatosSuperHeroes(){
        this.listSuperHeroes = new ArrayList<>();
        LeerArchivoHeroe lector2 = new LeerArchivoHeroe();
        try{
            if (lector2.abrirArchivo()) {
                //Se lee el objeto y se asigna al atributo de la clase VentanaPrincipal.
                listSuperHeroes = (ArrayList<Heroe>)lector2.leerArchivo();
                //Se cierra la conexión.
                lector2.cerrarArchivo();
            }
        }
        catch(Exception e){ 
            System.err.println("Error en leer archivo Heroe");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNombreHeroe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdentidadSecreta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSueldoEpisodio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarNombreHeroe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarSuperheroe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(187, 198, 220));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Superheroe");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 60));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBackground(new java.awt.Color(187, 198, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion del Superheroe", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreHeroe.setEditable(false);
        txtNombreHeroe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreHeroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreHeroeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 420, 30));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 440, 60));

        txtIdentidadSecreta.setEditable(false);
        txtIdentidadSecreta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtIdentidadSecreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 420, 30));

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identidad secreta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 440, 60));

        txtSueldoEpisodio.setEditable(false);
        txtSueldoEpisodio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSueldoEpisodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoEpisodioActionPerformed(evt);
            }
        });
        jPanel2.add(txtSueldoEpisodio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, 30));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sueldo por episodio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 280, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 480, 220));

        txtBuscarNombreHeroe.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPanel1.add(txtBuscarNombreHeroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 370, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del Superheroe a buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 390, 60));

        btnBuscarSuperheroe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscarSuperheroe.setText("Buscar");
        btnBuscarSuperheroe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarSuperheroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSuperheroeActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarSuperheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 150, 30));

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 560, 180));

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion del Superheroe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 580, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreHeroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreHeroeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreHeroeActionPerformed

    private void txtSueldoEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoEpisodioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoEpisodioActionPerformed

    private void btnBuscarSuperheroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSuperheroeActionPerformed
        String textBuscar = this.txtBuscarNombreHeroe.getText();
        boolean encontrado = false;
        if(!textBuscar.equals("")){
            for(Heroe heroe: listSuperHeroes){
                if(heroe.getNombre().toLowerCase().contains(textBuscar.toLowerCase())){
                    this.txtNombreHeroe.setText(heroe.getNombre());
                    this.txtIdentidadSecreta.setText(heroe.getIdSecreta());
                    this.txtSueldoEpisodio.setText(String.valueOf(heroe.calcularSueldo()));
                    this.txtDescripcion.setText(heroe.toString());
                    encontrado = true;
                }
            }
            if(!encontrado){
                JOptionPane.showMessageDialog(null, "Personaje no encontre en heroes","No texto",JOptionPane.WARNING_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Digite el nombre","No texto",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarSuperheroeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonajeHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonajeHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonajeHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonajeHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPersonajeHeroe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarSuperheroe;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarNombreHeroe;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtIdentidadSecreta;
    private javax.swing.JTextField txtNombreHeroe;
    private javax.swing.JTextField txtSueldoEpisodio;
    // End of variables declaration//GEN-END:variables
}
