/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */

public class JFrameAmiguitosLiga extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAmiguitosLiga
     */
    FondoPanel fondo = new FondoPanel();
    public JFrameAmiguitosLiga() { 
        //
        //this.setContentPane(new FondoPanel());
        //Evita que se pueda maximizar la pestaña
        this.setResizable(false);
        
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width/2, height/2);
        this.setLocationRelativeTo(null);
        
        
        initComponents();        
        this.txtFrase.setBackground(new Color(0,0,0,0));
        this.pnlInicio.setVisible(true);
        this.pnlEditar.setVisible(false);
        this.pnlBuscar.setVisible(false);
        this.pnlAgregar.setVisible(false);
        this.pnlResumen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlRoot = new FondoPanel();
        pnlCenter = new javax.swing.JPanel();
        pnlAgregar = new javax.swing.JPanel();
        btnAgregarPersonaje = new javax.swing.JButton();
        btnAgregarEpisodio = new javax.swing.JButton();
        btnAgregarSerie = new javax.swing.JButton();
        lblAgregar = new javax.swing.JLabel();
        btnAsignarRivales = new javax.swing.JButton();
        pnlEditar = new javax.swing.JPanel();
        btnEditarEpisodio = new javax.swing.JButton();
        btnEditarSerie = new javax.swing.JButton();
        btnEditarPersonaje = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        pnlBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarEpisodio = new javax.swing.JButton();
        btnBuscarVillano = new javax.swing.JButton();
        btnBuscarHeroe = new javax.swing.JButton();
        btnBuscarSerie = new javax.swing.JButton();
        pnlInicio = new FondoPanel();
        txtFrase = new javax.swing.JTextPane();
        pnlResumen = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnAgregarGnrl = new javax.swing.JButton();
        btnBuscarGnrl = new javax.swing.JButton();
        btnEditarGnrl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRoot.setPreferredSize(new java.awt.Dimension(500, 400));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlCenter.setBackground(new java.awt.Color(41, 41, 41));
        pnlCenter.setLayout(new javax.swing.OverlayLayout(pnlCenter));

        pnlAgregar.setBackground(new java.awt.Color(41, 41, 41));
        pnlAgregar.setPreferredSize(new java.awt.Dimension(420, 400));

        btnAgregarPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_administrator_50px_1.png"))); // NOI18N
        btnAgregarPersonaje.setText("Personaje");
        btnAgregarPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnAgregarPersonaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarPersonaje.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonajeActionPerformed(evt);
            }
        });

        btnAgregarEpisodio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_video_file_50px.png"))); // NOI18N
        btnAgregarEpisodio.setText("Episodio");
        btnAgregarEpisodio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnAgregarEpisodio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarEpisodio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarEpisodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEpisodioActionPerformed(evt);
            }
        });

        btnAgregarSerie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_video_playlist_50px.png"))); // NOI18N
        btnAgregarSerie.setText("Serie");
        btnAgregarSerie.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnAgregarSerie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarSerie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSerieActionPerformed(evt);
            }
        });

        lblAgregar.setBackground(new java.awt.Color(102, 102, 255));
        lblAgregar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(245, 245, 245));
        lblAgregar.setText("Menu Agregar");
        lblAgregar.setFocusable(false);

        btnAsignarRivales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_battle_50px_1.png"))); // NOI18N
        btnAsignarRivales.setText("Rivales");
        btnAsignarRivales.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnAsignarRivales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsignarRivales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAsignarRivales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarRivalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarLayout = new javax.swing.GroupLayout(pnlAgregar);
        pnlAgregar.setLayout(pnlAgregarLayout);
        pnlAgregarLayout.setHorizontalGroup(
            pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAgregarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarPersonaje)
                    .addComponent(btnAgregarSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarEpisodio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAsignarRivales, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(92, 92, 92))
        );
        pnlAgregarLayout.setVerticalGroup(
            pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarEpisodio)
                    .addComponent(btnAgregarPersonaje))
                .addGap(66, 66, 66)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarSerie)
                    .addComponent(btnAsignarRivales))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCenter.add(pnlAgregar);

        pnlEditar.setBackground(new java.awt.Color(41, 41, 41));
        pnlEditar.setPreferredSize(new java.awt.Dimension(400, 420));

        btnEditarEpisodio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_video_file_50px.png"))); // NOI18N
        btnEditarEpisodio.setText("Episodio");
        btnEditarEpisodio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnEditarEpisodio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarEpisodio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarEpisodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEpisodioActionPerformed(evt);
            }
        });

        btnEditarSerie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_video_playlist_50px.png"))); // NOI18N
        btnEditarSerie.setText("Serie");
        btnEditarSerie.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnEditarSerie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarSerie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSerieActionPerformed(evt);
            }
        });

        btnEditarPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_administrator_50px_1.png"))); // NOI18N
        btnEditarPersonaje.setText("Personaje");
        btnEditarPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnEditarPersonaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarPersonaje.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPersonajeActionPerformed(evt);
            }
        });

        lblEditar.setBackground(new java.awt.Color(102, 102, 255));
        lblEditar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEditar.setText("Menu Editar");
        lblEditar.setFocusable(false);

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnEditarPersonaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarEpisodio)
                .addGap(76, 76, 76))
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblEditar))
                    .addGroup(pnlEditarLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnEditarSerie)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarEpisodio)
                    .addComponent(btnEditarPersonaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarSerie)
                .addGap(124, 124, 124))
        );

        pnlCenter.add(pnlEditar);

        pnlBuscar.setBackground(new java.awt.Color(41, 41, 41));
        pnlBuscar.setPreferredSize(new java.awt.Dimension(420, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Busqueda");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnBuscarEpisodio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_video_file_50px.png"))); // NOI18N
        btnBuscarEpisodio.setText("Episodio");
        btnBuscarEpisodio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnBuscarEpisodio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarEpisodio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarEpisodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEpisodioActionPerformed(evt);
            }
        });

        btnBuscarVillano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_pennywise_50px.png"))); // NOI18N
        btnBuscarVillano.setText("Villano");
        btnBuscarVillano.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnBuscarVillano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarVillano.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarVillano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVillanoActionPerformed(evt);
            }
        });

        btnBuscarHeroe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_police_badge_50px.png"))); // NOI18N
        btnBuscarHeroe.setText("Heroe");
        btnBuscarHeroe.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnBuscarHeroe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarHeroe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarHeroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHeroeActionPerformed(evt);
            }
        });

        btnBuscarSerie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_video_playlist_50px.png"))); // NOI18N
        btnBuscarSerie.setText("Serie");
        btnBuscarSerie.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnBuscarSerie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarSerie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarVillano)
                            .addComponent(btnBuscarEpisodio))
                        .addGap(101, 101, 101)
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarHeroe)
                            .addComponent(btnBuscarSerie)))
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarEpisodio)
                    .addComponent(btnBuscarHeroe))
                .addGap(51, 51, 51)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarVillano)
                    .addComponent(btnBuscarSerie))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pnlCenter.add(pnlBuscar);

        pnlInicio.setBackground(new java.awt.Color(41, 41, 41));
        pnlInicio.setPreferredSize(new java.awt.Dimension(420, 400));

        txtFrase.setEditable(false);
        txtFrase.setBorder(null);
        txtFrase.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        txtFrase.setForeground(new java.awt.Color(255, 0, 102));
        txtFrase.setText("Nada derrota a Batman... excepto Batman");
        txtFrase.setAutoscrolls(false);
        txtFrase.setFocusable(false);
        txtFrase.setOpaque(false);

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        pnlCenter.add(pnlInicio);

        pnlResumen.setBackground(new java.awt.Color(41, 41, 41));
        pnlResumen.setPreferredSize(new java.awt.Dimension(450, 400));

        javax.swing.GroupLayout pnlResumenLayout = new javax.swing.GroupLayout(pnlResumen);
        pnlResumen.setLayout(pnlResumenLayout);
        pnlResumenLayout.setHorizontalGroup(
            pnlResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        pnlResumenLayout.setVerticalGroup(
            pnlResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlResumen);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        pnlSide.setBackground(new java.awt.Color(66, 72, 79));
        pnlSide.setToolTipText("");
        pnlSide.setPreferredSize(new java.awt.Dimension(80, 0));

        btnInicio.setBackground(new java.awt.Color(79, 66, 77));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_home_20px_1.png"))); // NOI18N
        btnInicio.setPreferredSize(new java.awt.Dimension(40, 40));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        pnlSide.add(btnInicio);

        btnAgregarGnrl.setBackground(new java.awt.Color(79, 66, 77));
        btnAgregarGnrl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_20px_3.png"))); // NOI18N
        btnAgregarGnrl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarGnrl.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAgregarGnrl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAgregarGnrlFocusGained(evt);
            }
        });
        btnAgregarGnrl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarGnrlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarGnrlMouseExited(evt);
            }
        });
        btnAgregarGnrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarGnrlActionPerformed(evt);
            }
        });
        pnlSide.add(btnAgregarGnrl);

        btnBuscarGnrl.setBackground(new java.awt.Color(79, 66, 77));
        btnBuscarGnrl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_20px_1.png"))); // NOI18N
        btnBuscarGnrl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarGnrl.setPreferredSize(new java.awt.Dimension(40, 40));
        btnBuscarGnrl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarGnrlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarGnrlMouseExited(evt);
            }
        });
        btnBuscarGnrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGnrlActionPerformed(evt);
            }
        });
        pnlSide.add(btnBuscarGnrl);

        btnEditarGnrl.setBackground(new java.awt.Color(79, 66, 77));
        btnEditarGnrl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_edit_20px.png"))); // NOI18N
        btnEditarGnrl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarGnrl.setEnabled(false);
        btnEditarGnrl.setPreferredSize(new java.awt.Dimension(40, 40));
        btnEditarGnrl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEditarGnrlFocusGained(evt);
            }
        });
        btnEditarGnrl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarGnrlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarGnrlMouseExited(evt);
            }
        });
        btnEditarGnrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarGnrlActionPerformed(evt);
            }
        });
        pnlSide.add(btnEditarGnrl);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.pnlInicio.setVisible(true);
        this.pnlEditar.setVisible(false);
        this.pnlBuscar.setVisible(false);
        this.pnlAgregar.setVisible(false);
        this.pnlResumen.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnAgregarGnrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGnrlActionPerformed
        if(pnlAgregar.isVisible()){
            pnlEditar.setVisible(false);
            pnlBuscar.setVisible(false);
        }
        else{
            pnlAgregar.setVisible(true);
            pnlEditar.setVisible(false);
            pnlBuscar.setVisible(false);
        }
    }//GEN-LAST:event_btnAgregarGnrlActionPerformed

    private void btnEditarGnrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarGnrlActionPerformed
        if(pnlEditar.isVisible()){
            pnlAgregar.setVisible(false);
            pnlBuscar.setVisible(false);
            
        }
        else{
            pnlEditar.setVisible(true);
            pnlAgregar.setVisible(false);
            pnlBuscar.setVisible(false);
        }
    }//GEN-LAST:event_btnEditarGnrlActionPerformed

    private void btnBuscarGnrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGnrlActionPerformed
        if(pnlBuscar.isVisible()){
            pnlAgregar.setVisible(false);
            pnlEditar.setVisible(false);   
        }
        else{
            pnlBuscar.setVisible(true);
            pnlAgregar.setVisible(false);
            pnlEditar.setVisible(false);
        }
    }//GEN-LAST:event_btnBuscarGnrlActionPerformed

    private void btnAgregarGnrlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarGnrlMouseEntered
        btnAgregarGnrl.setBackground(new Color(18, 30, 49));
    }//GEN-LAST:event_btnAgregarGnrlMouseEntered

    private void btnAgregarGnrlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarGnrlMouseExited
        btnAgregarGnrl.setBackground(new Color(79, 66, 77));
    }//GEN-LAST:event_btnAgregarGnrlMouseExited

    private void btnEditarGnrlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarGnrlMouseEntered
        btnEditarGnrl.setBackground(new Color(18, 30, 49));
    }//GEN-LAST:event_btnEditarGnrlMouseEntered

    private void btnEditarGnrlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarGnrlMouseExited
        btnEditarGnrl.setBackground(new Color(79, 66, 77));
    }//GEN-LAST:event_btnEditarGnrlMouseExited
    
    private void btnBuscarGnrlMouseEntered(java.awt.event.MouseEvent evt) {                                           
        btnBuscarGnrl.setBackground(new Color(18, 30, 49));
    }                                             

    private void btnBuscarGnrlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarGnrlMouseExited
        btnBuscarGnrl.setBackground(new Color(79, 66, 77));
    }//GEN-LAST:event_btnBuscarGnrlMouseExited

    private void btnEditarGnrlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEditarGnrlFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarGnrlFocusGained

    private void btnAgregarGnrlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAgregarGnrlFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarGnrlFocusGained
    
    private void btnAgregarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonajeActionPerformed
        // TODO add your handling code here:
        AgregarPersonaje ventana1 = new AgregarPersonaje();
        ventana1.jLabel1.setText("Agregar Personaje");
        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        //Evita Acumulamiento de ventanas y vuelve a abrir menu
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnAgregarPersonajeActionPerformed
    
    private void btnEditarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPersonajeActionPerformed
        // TODO add your handling code here:
        AgregarPersonaje ventana1 = new AgregarPersonaje();
        ventana1.jLabel1.setText("Editar Personaje");
        
        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        //Evita Acumulamiento de ventanas y vuelve a abrir menu
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnEditarPersonajeActionPerformed

    private void btnAgregarEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEpisodioActionPerformed
        // TODO add your handling code here:
        AgregarEpisodio ventana1 = new AgregarEpisodio();
        ventana1.jLabel1.setText("Agregar Episodio");

        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        //Evita Acumulamiento de ventanas y vuelve a abrir menu
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnAgregarEpisodioActionPerformed

    private void btnEditarEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEpisodioActionPerformed
        // TODO add your handling code here:
        AgregarEpisodio ventana1 = new AgregarEpisodio();
        ventana1.jLabel1.setText("Editar Episodio");

        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        //Evita Acumulamiento de ventanas y vuelve a abrir menu
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnEditarEpisodioActionPerformed

    private void btnAgregarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSerieActionPerformed
        // TODO add your handling code here:
        AgregarSerie ventana1 = new AgregarSerie();
        ventana1.jLabel1.setText("Agregar Serie");
        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        //Evita Acumulamiento de ventanas y vuelve a abrir menu
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnAgregarSerieActionPerformed

    private void btnEditarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSerieActionPerformed
        // TODO add your handling code here:
        AgregarSerie ventana1 = new AgregarSerie();
        ventana1.jLabel1.setText("Editar Serie");
        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        //Evita Acumulamiento de ventanas y vuelve a abrir menu
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnEditarSerieActionPerformed

    private void btnBuscarEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEpisodioActionPerformed
        BuscarEpisodio ventana1 = new BuscarEpisodio();
        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnBuscarEpisodioActionPerformed

    private void btnBuscarVillanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVillanoActionPerformed
        BuscarPersonajeVillano ventana1 = new BuscarPersonajeVillano();
        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnBuscarVillanoActionPerformed

    private void btnBuscarHeroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHeroeActionPerformed
       BuscarPersonajeHeroe ventana1 = new BuscarPersonajeHeroe();
        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnBuscarHeroeActionPerformed

    private void btnAsignarRivalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarRivalesActionPerformed
        AsignarRivales ventana1 = new AsignarRivales();
        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnAsignarRivalesActionPerformed

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        btnInicio.setBackground(new Color(18, 30, 49));
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        btnInicio.setBackground(new Color(79, 66, 77));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnBuscarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSerieActionPerformed
        MostrarInformacion ventana1 = new MostrarInformacion();
        ventana1.setVisible(true); //hace visible el JFrame de la ventana de agregar serie.
        ventana1.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        ventana1.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnBuscarSerieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAmiguitosLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAmiguitosLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAmiguitosLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAmiguitosLiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAmiguitosLiga().setVisible(true);
            }
        });
    }
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEpisodio;
    private javax.swing.JButton btnAgregarGnrl;
    private javax.swing.JButton btnAgregarPersonaje;
    private javax.swing.JButton btnAgregarSerie;
    private javax.swing.JButton btnAsignarRivales;
    private javax.swing.JButton btnBuscarEpisodio;
    private javax.swing.JButton btnBuscarGnrl;
    private javax.swing.JButton btnBuscarHeroe;
    private javax.swing.JButton btnBuscarSerie;
    private javax.swing.JButton btnBuscarVillano;
    private javax.swing.JButton btnEditarEpisodio;
    private javax.swing.JButton btnEditarGnrl;
    private javax.swing.JButton btnEditarPersonaje;
    private javax.swing.JButton btnEditarSerie;
    private javax.swing.JButton btnInicio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JPanel pnlAgregar;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlResumen;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JTextPane txtFrase;
    // End of variables declaration//GEN-END:variables
    public class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/images/Batman.jpeg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    private WindowListener reAbrir() {
        WindowAdapter adapter = new WindowAdapter(){
                @Override
                public void windowClosing(WindowEvent we){
                    JFrameAmiguitosLiga nuevo = new JFrameAmiguitosLiga();
                    nuevo.setVisible(true);
                }
            };
        return adapter;
    }
}
